Add RKE1 CIS 1.24 Configs
rancher/security-scan pull request #117
Opened 2023-04-11 14:39 UTC by rayandas

Related: https://github.com/rancher/cis-operator/issues/190

This PR adds below configs:

- cis-1.24
- rke-cis-1.24-permissive
- rke-cis-1.24-hardened

2023-06-22 14:33 UTC, andypitcher approved these changes

2023-06-27 17:05 UTC, JonCrowther requested changes
Very minor grammar fix

2023-06-27 17:05 UTC, JonCrowther commented on package/cfg/rke-cis-1.23-permissive/master.yaml
> +          Cluster provisioned by RKE does not store the kubernetes default kubeconfig credentials file on the nodes.
Similarly
```suggestion
          A cluster provisioned by RKE does not store the kubernetes default kubeconfig credentials file on the nodes.
```
or
```suggestion
          Clusters provisioned by RKE do not store the kubernetes default kubeconfig credentials file on the nodes.
```

2023-06-28 14:10 UTC, JonCrowther approved these changes

2023-06-28 14:30 UTC, merged