Fix rke2 cis 1.7 check errors
rancher/security-scan pull request #153
Opened 2023-08-11 15:53 UTC by JonCrowther

Addresses: https://github.com/rancher/rancher/issues/42385

Fix errors in rke2 cis 1.7 hardened and permissive checks

2023-08-14 13:48 UTC, doflamingo721 approved these changes

2023-08-14 18:32 UTC, KevinJoiner commented
@andypitcher do we gain anything from using the kube-bench version? It seems they are using a variable because there are multiple locations for scheduler yaml which differed from RKE2.

2023-08-15 15:59 UTC, KevinJoiner requested changes

2023-08-15 15:59 UTC, KevinJoiner commented on package/cfg/rke2-cis-1.7-hardened/master.yaml
> +        audit: "/bin/sh -c 'if test -e $controllermanagerkubeconfig; then stat -c permissions=%a $controllermanagerkubeconfig; fi'"
You will need to also add a kubeconfig field under the `controllermanager` sectuib in `config.yaml` for this one to work.

2023-08-15 15:59 UTC, KevinJoiner commented on package/cfg/rke2-cis-1.7-permissive/master.yaml
> +        audit: "/bin/sh -c 'if test -e $controllermanagerkubeconfig; then stat -c permissions=%a $controllermanagerkubeconfig; fi'"
same as above

2023-08-15 16:06 UTC, KevinJoiner approved these changes

2023-08-15 16:58 UTC, pjbgf approved these changes

2023-08-15 17:08 UTC, pdellamore approved these changes

2023-08-15 17:45 UTC, merged