Use variables instead of hardcoded values when possible in RKE2 CIS
rancher/security-scan pull request #217
Opened 2024-07-12 18:14 UTC by dereknola

Various fixes for RKE2 cis scans:
- Add missing 1.1.7 and 1.1.8 checks. We pass theses automatically, I am unsure why they were never included.
- Use variables instead of hard-coding values in scans, includes things like etcd data dir, various kubeconfigs,
- Replace generic and incorrect K8s "remediation" with RKE2 specific remediation that match the actual audit.

2024-07-18 20:16 UTC, andypitcher requested changes

2024-07-18 20:16 UTC, andypitcher commented on package/cfg/rke2-cis-1.23-hardened/master.yaml
> +        use_multiple_values: true
```suggestion
        audit: "/bin/sh -c 'if test -e $etcdconf; then stat -c permissions=%a $etcdconf; fi'"
```
IIRC There is only one pod manifest/config in RKE2 `/var/lib/rancher/k3s/server/db/etcd/config` so we don't need to use this `mutiple_values` approach  and the `find $etcdconf -name '*etcd*' `  seems wrong, as will not return anything.
<img width="722" alt="image" src="https://github.com/user-attachments/assets/6f1b21e1-693e-490c-9269-d8c5efc98901">

2024-07-18 20:16 UTC, andypitcher commented on package/cfg/rke2-cis-1.24-hardened/master.yaml
> +        audit: "/bin/sh -c 'if test -e $etcdconf; then find $etcdconf -name '*etcd*' | xargs stat -c permissions=%a; fi'"
```suggestion
        audit: "/bin/sh -c 'if test -e $etcdconf; then stat -c permissions=%a $etcdconf; fi'"
```

2024-07-18 20:16 UTC, andypitcher commented on package/cfg/rke2-cis-1.7-hardened/master.yaml
> +        use_multiple_values: true
```suggestion
        audit: "/bin/sh -c 'if test -e $etcdconf; then stat -c permissions=%a $etcdconf; fi'"
```

2024-07-18 20:16 UTC, andypitcher commented on package/cfg/rke2-cis-1.24-permissive/master.yaml
> +        audit: "/bin/sh -c 'if test -e $etcdconf; then find $etcdconf -name '*etcd*' | xargs stat -c permissions=%a; fi'"
```suggestion
        audit: "/bin/sh -c 'if test -e $etcdconf; then stat -c permissions=%a $etcdconf; fi'"
```

2024-07-18 20:16 UTC, andypitcher commented on package/cfg/rke2-cis-1.7-permissive/master.yaml
> +        use_multiple_values: true
```suggestion
        audit: "/bin/sh -c 'if test -e $etcdconf; then stat -c permissions=%a $etcdconf; fi'"
```

2024-07-18 20:16 UTC, andypitcher commented on package/cfg/rke2-cis-1.8-hardened/master.yaml
> +        use_multiple_values: true
```suggestion
        audit: "/bin/sh -c 'if test -e $etcdconf; then stat -c permissions=%a $etcdconf; fi'"
```

2024-07-18 20:16 UTC, andypitcher commented on package/cfg/rke2-cis-1.8-permissive/master.yaml
> +        use_multiple_values: true
```suggestion
        audit: "/bin/sh -c 'if test -e $etcdconf; then stat -c permissions=%a $etcdconf; fi'"
```

2024-07-19 18:38 UTC, andypitcher approved these changes

2024-07-30 14:45 UTC, pjbgf approved these changes

2024-07-30 14:45 UTC, merged