rke2: set type:manual for audit log checks in permissive profiles
rancher/security-scan pull request #242
Opened 2024-08-26 13:09 UTC by vardhaman22

set  `type: manual` to audit log related checks for rke2 permissive profiles
following checks are updated
- rke2-cis-1.8-profile-permissive 1.2.17-20
- rke2-cis-1.7-profile-permissive 1.2.18-21
- rke2-cis-1.23-profile-permissive 1.2.19-22
- rke2-cis-1.24-profile-permissive 1.2.19-22

Since type manual is set, these tests will always be in warn state for these profiles after this change.

2024-08-28 15:23 UTC, andypitcher requested changes

2024-08-29 13:50 UTC, andypitcher approved these changes
LGTM !

2024-08-29 14:18 UTC, vardhaman22 commented on package/cfg/rke2-cis-1.23-permissive/master.yaml
>          text: "Ensure that the --audit-log-path argument is set (Automated)"
done

2024-08-29 14:18 UTC, vardhaman22 commented on package/cfg/rke2-cis-1.23-permissive/master.yaml
>          text: "Ensure that the --audit-log-maxage argument is set to 30 or as appropriate (Automated)"
done

2024-08-29 14:18 UTC, vardhaman22 commented on package/cfg/rke2-cis-1.23-permissive/master.yaml
>          text: "Ensure that the --audit-log-maxbackup argument is set to 10 or as appropriate (Automated)"
done

2024-08-29 14:18 UTC, vardhaman22 commented on package/cfg/rke2-cis-1.23-permissive/master.yaml
>          text: "Ensure that the --audit-log-maxsize argument is set to 100 or as appropriate (Automated)"
done

2024-08-29 15:04 UTC, merged