rke2 fix failed checks for permissive profiles
rancher/security-scan pull request #247
Opened 2024-09-04 14:50 UTC by vardhaman22

issue: https://github.com/rancher/rancher/issues/46812 and https://github.com/rancher/cis-operator/issues/350
1.1.1, 1.1.3 and 1.1.5 checks were marked as scored: false for 1.8 permissive profile in PR: https://github.com/rancher/security-scan/pull/231
Updated these checks for the other rke2 permissive profiles based on that.

2024-09-04 16:29 UTC, dereknola requested changes
These checks pass in my testing. Are you setting `profile: cis` in the RKE2 config?

2024-09-04 17:12 UTC, vardhaman22 commented
> These checks pass in my testing. Are you setting `profile: cis` in the RKE2 config?
The profile cis option was not used. We run permissive profile checks on non hardened clusters. these checks were earlier documented as expected failures. But the above mentioned [PR](https://github.com/rancher/security-scan/pull/231) set them to `scored: false` for 1.8 profile i have updated the other permissive profiles as well to keep them in sync.

2024-09-05 20:53 UTC, andypitcher approved these changes

2024-09-05 20:54 UTC, dereknola approved these changes

2024-09-06 01:47 UTC, merged