Fix scan failures after updating kube-bench to v0.6.8 and Go version to 1.17
rancher/security-scan pull request #88
Opened 2022-07-05 13:01 UTC by rayandas

TODO: Describe all the test failure fixes and attach snapshot of tests. 
NOTE: Need to rebase after the following PRs gets merged https://github.com/rancher/security-scan/pull/85, and https://github.com/rancher/security-scan/pull/86

2022-07-06 16:33 UTC, rancher-max requested changes
For failing check 1.1.13 in rke2, I believe we should set `op: eq` instead of `bitmask`. The check itself shouldn't fail, and setting the op to eq would make it consistent with 1.1.11 for example.
Ref:
https://docs.rke2.io/security/cis_self_assessment16/#1113

```
$ sudo stat -c permissions=%a /var/lib/rancher/rke2/server/cred/admin.kubeconfig
permissions=644
```

2022-07-07 05:04 UTC, rayandas commented
In RKE2 1.23 profiles (hardened and permissive) the check is "Ensure that the admin.conf file permissions are set to 600 or more restrictive", see https://github.com/rancher/security-scan/blob/master/package/cfg/rke2-cis-1.23-permissive/master.yaml#L131-L143
That's why the value is set to 600 and the operator is bitmask. But when we logged into the node and checked the permission, it's 644. that's why the check is failing for 1.23 profiles. and it's genuine.

2022-07-08 09:26 UTC, prachidamle commented
What are the node permissions on a node for rke1, wonder how the test 1.1.13 passes on rke1? Are they already at 600?

2022-07-08 09:54 UTC, rayandas commented
I see the test 1.1.13 is marked as skip in rke1 1.23 profile. The test has 600 permission check as well. 
So should we update it to 644? (and remove skip for rke1 1.23 profile?)

2022-07-11 05:13 UTC, prachidamle commented
> I see the test 1.1.13 is marked as skip in rke1 1.23 profile. The test has 600 permission check as well. So should we update it to 644? (and remove skip for rke1 1.23 profile?)

Yes that sounds good. We should document this change ("600" to "644") in release notes for our scan profiles.

2022-07-11 11:40 UTC, rayandas commented
@prachidamle I have updated RKE2 1.23 check 1.1.13 to 644 now. And it's passing. 
For RKE1 1.1.13 check is not applicable that's why it's marked as skipped. The reason is "Cluster provisioned by RKE does not store the kubernetes default kubeconfig credentials file on the nodes." and the PR that added skip for 1.1.13 is this https://github.com/rancher/security-scan/commit/70215d5aa77e8ab1b15a4bf2e59a66bcc99aa440

2022-07-11 15:50 UTC, rancher-max submitted a review, later dismissed

2022-07-11 16:07 UTC, prachidamle approved these changes

2022-07-12 07:24 UTC, rayandas commented
Rebased after merging the PR #85

2022-07-12 07:52 UTC, samkulkarni20 approved these changes
Approving the rebase. @prachidamle & @rancher-max had previously approved this PR.

2022-07-12 07:53 UTC, merged