Fix for 5.3.1 scans failing for calico, cilium CNI
rancher/security-scan pull request #91
Opened 2022-07-21 05:11 UTC by mitul777

[https://github.com/rancher/cis-operator/issues/154](https://github.com/rancher/cis-operator/issues/154)

Fix for 5.3.1 scans failing for calico and cilium CNIs

2022-08-29 17:25 UTC, aiyengar2 requested changes
nit: I think we should stick with `kubectl get pods` instead of `kubectl get po` for code readability

2022-08-29 17:25 UTC, aiyengar2 commented on package/cfg/rke2-cis-1.20-hardened/policies.yaml
> +        audit: "kubectl get po --all-namespaces --selector='k8s-app in (calico-node, canal, cilium)' -o name | wc -l | xargs -I {} echo '--count={}'"
nit:

```suggestion
        audit: "kubectl get pods --all-namespaces --selector='k8s-app in (calico-node, canal, cilium)' -o name | wc -l | xargs -I {} echo '--count={}'"
```

2022-08-29 17:25 UTC, aiyengar2 commented on package/cfg/rke2-cis-1.6-hardened/policies.yaml
> +        audit: "kubectl get po --all-namespaces --selector='k8s-app in (calico-node, canal, cilium)' -o name | wc -l | xargs -I {} echo '--count={}'"
nit:

```suggestion
        audit: "kubectl get pods --all-namespaces --selector='k8s-app in (calico-node, canal, cilium)' -o name | wc -l | xargs -I {} echo '--count={}'"
```

2022-08-30 12:05 UTC, mitulshah-suse commented on package/cfg/rke2-cis-1.6-hardened/policies.yaml
> +        audit: "kubectl get po --all-namespaces --selector='k8s-app in (calico-node, canal, cilium)' -o name | wc -l | xargs -I {} echo '--count={}'"
updated as suggested

2022-08-30 12:05 UTC, mitulshah-suse commented on package/cfg/rke2-cis-1.5-hardened/policies.yaml
> +      audit: "kubectl get po --all-namespaces --selector='k8s-app in (calico-node, canal, cilium)' -o name | wc -l | xargs -I {} echo '--count={}'"
updated as suggested

2022-08-30 12:05 UTC, mitulshah-suse commented on package/cfg/rke2-cis-1.23-hardened/policies.yaml
> +        audit: "kubectl get po --all-namespaces --selector='k8s-app in (calico-node, canal, cilium)' -o name | wc -l | xargs -I {} echo '--count={}'"
updated as suggested

2022-08-30 12:05 UTC, mitulshah-suse commented on package/cfg/rke2-cis-1.20-hardened/policies.yaml
> +        audit: "kubectl get po --all-namespaces --selector='k8s-app in (calico-node, canal, cilium)' -o name | wc -l | xargs -I {} echo '--count={}'"
updated as suggested

2022-08-30 18:47 UTC, aiyengar2 approved these changes

2022-09-01 06:54 UTC, merged